from .catfish import Catfish
from .donkey import Donkey
from .eel import Eel
from .garter_snake import GarterSnake
from .goat import Goat
from .green_snake import GreenSnake
from .king_snake import KingSnake
from .llama import Llama
from .miniature_horse import MiniatureHorse
from .python import Python
from .rat_snake import RatSnake
from .sheep import Sheep
from .sting_ray import StingRay
from .tiger_shark import TigerShark
from .tuna import Tuna
